### ISSUE TITLE
Ensure out-of-scope commands cannot be used through PMs

### ISSUE THREAD

**Issue by TheSonAlsoRises** [pokemontrades/porygon-bot#52]
On top of #51: users with limited permissions must not be able to use restricted commands by PMing the bot.

**Comment by not-an-aardvark** [comment]
This should be fine since the usernote command doesn't work by PM anyway.

**Comment by Raia** [comment]
There isn't really a reason to use .search through PM, so I'll at least restrict that.

The rest of the commands relevant to this issue are untracked by Git, but I can take care of them.
