### ISSUE TITLE
Capital O in O/ breaks other high fives

### ISSUE THREAD

**Issue by Raia** [pokemontrades/porygon-bot#72]
It seems to act as a `\o` but I'm not sure?

**Comment by YaManicKill** [comment]
Yup, that makes sense based on the code.

The regex is case insensitive, so it gets `o/`, `\o`, `O/`, and `\O`, but then the [direction logic](https://github.com/pokemontrades/porygon-bot/blob/master/commands/highfive.js#L16) only checks for `o/`.
